version: "3.9"

services:
  chokdi-backend:
    image: rew1234/chokdi-backend:V3.0
    
    ports:
      - "5004:5004"
    environment:

      DB_HOST: database-1.cxsc0uqkcji7.ap-southeast-1.rds.amazonaws.com
      DB_USER: root
      DB_PASSWORD: riew2545
      DB_DATABASE: Chokdi2
      DB_PORT: 3306 
      SERVER_PORT: 5004
      JWT_SECRET: JWT_SECRET
      ALLOW_REQUEST_IP: "http://ec2-13-250-40-24.ap-southeast-1.compute.amazonaws.com:5005" 

    restart: always

  chokdi-frontend:
    image: rew1234/chokdi-frontend:V3.0
    ports:
      - "5005:5005"
    environment:
      SERVER_PORT: 5005
      SERVER_HOST: "0.0.0.0"
      VITE_API_PORT: 5004
      VITE_API_HOST_IP: "ec2-13-250-40-24.ap-southeast-1.compute.amazonaws.com"     #YOOOO localhost -> not full aws url (chokdi)
      VITE_GOOGLE_CLIENT_ID: 658254688251-57jm5pokhi21fcs72ecqo0e05u1dohku.apps.googleusercontent.com
    depends_on:
      - chokdi-backend
