version: "3.9"

services:
  mysql-chokdi:
    image: mysql
    volumes:
      - /path/to/empty/directory:/var/lib/mysql
      # - mysql_data:/var/lib/mysql
      - ./CustomerInsurance.sql:/docker-entrypoint-initdb.d/CustomerInsurance.sql
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "ec2-13-250-40-24.ap-southeast-1.compute.amazonaws.com"]   #YOOOO localhost -> not full aws url chokdi
      interval: 15s
      timeout: 5s
      retries: 3
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container-compose-chokdi
    depends_on:
      - mysql-chokdi
    links:
      - mysql-chokdi:db
    ports:
      - "8082:80"
    restart: always

  chokdi-backend:
    image: rew1234/chokdi-backend:V1.0
    
    ports:
      - "5004:5004"
    environment:
      DB_HOST: mysql-chokdi
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: Chokdi2
      DB_PORT: 3306 
      SERVER_PORT: 5004
      JWT_SECRET: JWT_SECRET
      ALLOW_REQUEST_IP: "http://ec2-13-250-40-24.ap-southeast-1.compute.amazonaws.com:5005" #YOOOO full+port (http://chokdi:5005)
    depends_on:
      mysql-chokdi:
        condition: service_healthy
    restart: always

  chokdi-frontend:
    image: rew1234/chokdi-frontend:V1.0
    ports:
      - "5005:5005"
    environment:
      SERVER_PORT: 5005
      SERVER_HOST: "0.0.0.0"
      VITE_API_PORT: 5004
      VITE_API_HOST_IP: "ec2-13-250-40-24.ap-southeast-1.compute.amazonaws.com"     #YOOOO localhost -> not full aws url (chokdi)
      VITE_GOOGLE_CLIENT_ID: 658254688251-57jm5pokhi21fcs72ecqo0e05u1dohku.apps.googleusercontent.com
    depends_on:
      - chokdi-backend
volumes:
  mysql_data:

  