version: "3.9"

services:
  mysql-chokdi:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./CustomerInsurance.sql:/docker-entrypoint-initdb.d/CustomerInsurance.sql
      # - /Users/reviseuc73/Desktop/Project/Chokdi/CustomerInsurance.sql:/docker-entrypoint-initdb.d/CustomerInsurance.sql
      
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container-compose-chokdi
    depends_on:
      - mysql-chokdi
    links:
      - mysql-chokdi:db
    ports:
      - "8082:80"
    restart: always
  

  chokdi-backend:
    image: rew1234/chokdi-backend:V1.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5004/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5004:5004"
    environment:
      DB_HOST: mysql-chokdi
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: Chokdi
      DB_PORT: 3306 
      SERVER_PORT: 5004
      JWT_SECRET: JWT_SECRET
      FRONTEND_IP: "http://localhost:5005"
    depends_on:
      mysql-chokdi:
        condition: service_healthy
    networks:
      - sql_network
    restart: always

  chokdi-frontend:
    image: rew1234/chokdi-frontend:V1.0
    ports:
      - "5005:5005" 
    environment:
      SERVER_PORT: 5005
      SERVER_HOST: "0.0.0.0"
      VITE_API_PORT: 5004
      VITE_API_HOST_IP: "localhost"
      VITE_GOOGLE_CLIENT_ID: 658254688251-57jm5pokhi21fcs72ecqo0e05u1dohku.apps.googleusercontent.com

    depends_on:
      - chokdi-backend
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge


volumes:
  mysql_data:


